#!/usr/bin/env php
<?php
require __DIR__ . '/src/bootstrap.php';
$app=SRESTO\Tools\Console\ConsoleRunner::createApplication();
$app->add(new SRESTO\Tools\Console\Commands\SchemaCommand($entityManager));
$app->run();